version: 0.2

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Serverless CLI
      - npm i -g serverless@3
      - echo Installing NPM dependencies
      - npm i
  build:
    on-failure: ABORT
    commands:
      - echo Deploying resources
      #      - serverless deploy --stage dev
      - serverless deploy --package my-artifact --stage dev
# test
artifacts:
  files:
    - my-artifact/*
  name: MyProjectArtifacts
cache:
  paths:
    - 'node_modules/**/*'
